export const GET_GIT_REPO = "GET_GIT_REPO";
export const GET_GIT_REPO_REQUESTED = "GET_GIT_REPO_REQUESTED";
export const GET_GIT_REPO_STATUS = "GET_GIT_REPO_STATUS";
export const GET_GIT_REPO_STATUS_REQUESTED = "GET_GIT_REPO_STATUS_REQUESTED";
